#!/usr/bin/env bash
# Render ~/.hermes/config.yaml from the environment on every start, so the
# container stays declarative: edit .env, restart, done.
set -euo pipefail

HERMES_DIR="${HERMES_HOME:-/root/.hermes}"
mkdir -p "$HERMES_DIR"

LLM_BASE_URL="${LLM_BASE_URL:?set LLM_BASE_URL, e.g. http://10.150.0.30:1234/v1}"
LLM_MODEL="${LLM_MODEL:?set LLM_MODEL}"
LLM_API_KEY="${LLM_API_KEY:-local}"
PRICEWATCH_MCP_URL="${PRICEWATCH_MCP_URL:-http://pricewatch:8000/mcp}"
# Declare the model's real window (Hermes refuses anything under 64K), but cap the
# output request: left to itself Hermes asks for max_tokens == context_length, and
# vLLM requires prompt + max_tokens <= max_model_len, so every call would fail once
# and retry. LLM_MAX_TOKENS keeps each request inside the window on the first try.
LLM_CONTEXT_LENGTH="${LLM_CONTEXT_LENGTH:-65536}"
LLM_MAX_TOKENS="${LLM_MAX_TOKENS:-8192}"

cat > "$HERMES_DIR/config.yaml" <<YAML
# Generated by entrypoint.sh — edit .env and restart rather than editing this file.
model:
  provider: custom
  default: ${LLM_MODEL}
  base_url: ${LLM_BASE_URL}
  api_key: ${LLM_API_KEY}
  context_length: ${LLM_CONTEXT_LENGTH}
  max_tokens: ${LLM_MAX_TOKENS}
  timeout: 300

mcp_servers:
  pricewatch:
    transport: http
    url: ${PRICEWATCH_MCP_URL}
    enabled: true
    timeout: 120
YAML

# Ship the shopping skill into the agent's skill directory.
if [ -d /opt/hermes-skills ]; then
  mkdir -p "$HERMES_DIR/skills"
  cp -r /opt/hermes-skills/. "$HERMES_DIR/skills/" 2>/dev/null || true
fi

# The dashboard binds off loopback, and Hermes requires an auth provider for that.
# Fail loudly here rather than letting the server start unreachable or unprotected.
if [ "${1:-}" = "hermes" ] && [ "${2:-}" = "dashboard" ]; then
  if [ -z "${HERMES_DASHBOARD_BASIC_AUTH_PASSWORD:-}" ] && \
     [ -z "${HERMES_DASHBOARD_BASIC_AUTH_PASSWORD_HASH:-}" ]; then
    echo "ERROR: the dashboard needs a password before it can bind to 0.0.0.0." >&2
    echo "  Set these in .env, then re-run 'docker compose up -d dashboard':" >&2
    echo "    HERMES_DASHBOARD_BASIC_AUTH_USERNAME=admin" >&2
    echo "    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD=<choose one>" >&2
    exit 1
  fi
fi

# Wait for the price engine so the first MCP handshake succeeds.
for _ in $(seq 1 30); do
  if curl -fsS "${PRICEWATCH_HEALTH_URL:-http://pricewatch:8000/api/health}" >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

exec "$@"
